### ISSUE TITLE
ZAP execution using pipeline

### ISSUE THREAD

**Issue by arslanjavaid1** [vrondakis/zap-jenkins-pipeline-plugin#2] opened 2018-09-11 15:29 UTC
There is no documentation on the plug in to used in Jenkins. How are we suppose to use it after the install?

**Comment by vrondakis** [comment] 2018-09-11 15:30
Check the readme? All the functions are listed there

**Comment by arslanjavaid1** [comment] 2018-09-11 15:43
How i can use those functions in Jenkins? while configuring the job? Or is it an API which i have to use? I am not clear on that. Sorry

**Comment by vrondakis** [comment] 2018-09-12 08:02
No problem, what's the exact error? If you are getting "zap-comp: Failed to start ZAP process" then it's probably because zapHome (param in startZap) isn't the location of your ZAP installation - mine is at /opt/zap

**Comment by arslanjavaid1** [comment] 2018-09-12 13:39
Thats exactly my issue however, when i run the same script in CMD it is running fine. But of pipeline it is not running

**Comment by vrondakis** [comment] 2018-09-12 13:53
Are you running Windows?

**Comment by arslanjavaid1** [comment] 2018-09-12 13:54
Image has been attached
![issue zap pipeline](https://user-images.githubusercontent.com/33438857/45429692-6c52ff00-b669-11e8-8f84-bcdef5308636.PNG)

**Comment by arslanjavaid1** [comment] 2018-09-12 14:27
@vrondakis It is missing hpi file for jenkins. Or should i generate it?

**Comment by vrondakis** [comment] 2018-09-12 14:31
Failed to upload, try again

**Comment by arslanjavaid1** [comment] 2018-09-12 14:33
Trying. Hope it works.

**Comment by arslanjavaid1** [comment] 2018-09-12 16:11
@vrondakis i am still getting the same issue that 
```Java
zap-comp: Failed to shutdown ZAP (it's not running?)
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
[Office365connector] No webhooks to notify
java.lang.Throwable: zap-comp: Failed to start ZAP process
	at com.barracuda.zapcomp.workflow.StartZapExecution.start(StartZapExecution.java:68)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:229)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:153)

```

**Comment by arslanjavaid1** [comment] 2018-09-12 16:59
I have changed the ZAP version and was able to move forward however, i got another error:

![issue zap pipeline](https://user-images.githubusercontent.com/33438857/45440938-4e929380-b683-11e8-984e-650ba4a0a0d9.PNG)

**Comment by vrondakis** [comment] 2018-09-12 18:04
That timeout is for when ZAP makes a request. Copy the zap.bat line into cmd and try running your build again to see if it's failing to start

**Comment by arslanjavaid1** [comment] 2018-09-12 18:26
@vrondakis i tried that and it is working as it is saying listening on the port.

**Comment by vrondakis** [comment] 2018-09-13 07:19
If you then run the build with ZAP running (with the same settings), do you still see the socket timed out message? Could you please try [this](http://manolisvrondakis.com/zap-comp.hpi) HPI file, run your build & check your Jenkins log file (not the console log)

**Comment by arslanjavaid1** [comment] 2018-09-13 13:36
@vrondakis  I was able to resolve socket issue. Then i came across the JAVA IO issue with the crawler

**Comment by vrondakis** [comment] 2018-09-13 13:39
How did you resolve it, what was wrong?

~What Java IO issue with the crawler?

**Comment by arslanjavaid1** [comment] 2018-09-13 13:46
The issue was being caused by the location of zap. When i moved the zap installation into jenkins workspace and gave zaphome blank, it worked. However, then i came across the Crawler issue. The crawler was not working. The crawler wasn't able to crawl the app because of some issue. I dont remember exactly now since i deleted the project.

**Comment by arslanjavaid1** [comment] 2018-09-13 13:49
@vrondakis  If you need help in maintaining the repo, i can help to contribute.

**Comment by vrondakis** [comment] 2018-09-13 13:56
Seems like you could have used a relative path and not an absolute path as your zapHome. You shouldn't really have the ZAP program in your workspace.
The startZapCrawler function just starts ZAPs crawler on a specific host, can you run the crawler on the project normally? 

Please feel free to contribute :)

**Comment by arslanjavaid1** [comment] 2018-09-13 15:04
@vrondakis  i tried to use relative path in ZapHome but it was not working because when i was trying to run it, it was giving error that this path is not valid in windows.

**Comment by vrondakis** [comment] 2018-09-13 15:07
Can you send me the startZap line you tried to use?

**Comment by arslanjavaid1** [comment] 2018-09-13 15:11
If i move zap to home directory of workspace
```Java
startZap(host: '127.0.0.1', port: 9091, timeout:500, zapHome: "", sessionPath:"/session.session", allowedHosts:[''])
```

**Comment by vrondakis** [comment] 2018-09-13 15:16
The one that didn't work if you still have it?

**Comment by arslanjavaid1** [comment] 2018-09-13 15:30
well the structure where i was trying this was not local. It is completely distributed jenkins deployment on various nodes. I mentioned the node where i wanted my zap to be  build. I implemented the pipeline and add the zap folder with absolute path since relative would have only worked if i would have added that to the workspace for pipeline. If i add it to zap workspace and add give `zaphome '/zap.2.7.0'` this will fail it.

**Comment by vrondakis** [comment] 2018-09-21 08:17
Closing due to no reply, feel free to re-open

**Closed by vrondakis** 2018-09-21 08:17 UTC

**Comment by hieund12** [comment] 2019-05-08 02:30
@vrondakis 

I have problem when I run  > runZapCrawler(host: "https://localhost")
I don't set // sh "mvn verify -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=8080 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=8080" // Proxy tests through ZAP

I only start zap: > startZap(host: "127.0.0.1", port: 8080, zapHome: "C:/Users/Administrator/.jenkins/tools/com.cloudbees.jenkins.plugins.customtools.CustomTool/zap/ZAP_2.7.0", allowedHosts:['127.0.0.1:8080'])

And now I can't start crawler
.....
zap: Starting crawler on host https://localhost...
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.lang.Throwable: zap: Failed to start ZAP crawler on host https://localhost
	at com.vrondakis.zap.workflow.RunZapCrawlerExecution.start(RunZapCrawlerExecution.java:37)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:268)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:176)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
	at sun.reflect.GeneratedMethodAccessor1807.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:158)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:155)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:156)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:160)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:130)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:130)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:57)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:82)
	at sun.reflect.GeneratedMethodAccessor241.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
	at sun.reflect.GeneratedMethodAccessor263.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$101(SandboxContinuable.java:34)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.lambda$run0$0(SandboxContinuable.java:59)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:136)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:58)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:182)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:332)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:83)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:244)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:232)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
....
I want o create simple demo ZAP execution using pipeline.
Could you give me some advice?
Thank you

**Comment by vasanthaneppali** [comment] 2022-04-30 18:04
@hieund12 
Hi, Facing the same issue was it resolved?
if yes please share
Thank you

**Comment by vasanthaneppali** [comment] 2022-05-02 12:17
@uen 
Fcaing the same error  mentioned by @hieund12 please help to solve the issue
Thank you

**Comment by shardy-lbar** [comment] 2022-05-03 08:18
@vasanthaneppali

This repo is now deprecated. The plugin has been accepted into the jenkins plugin library, and the repo is now located here:

https://github.com/jenkinsci/zap-pipeline-plugin

Please use the latest version from the marketplace to ensure your issue has not already been fixed. If your issue still persists, then please open a new ticket there, listing full details and if possible a way to reproduce the issue.
